language: java
matrix:
  include:
  - jdk: openjdk8
    env: GRADLE_PUBLISH=true
  - jdk: openjdk11
    env: GRADLE_PUBLISH=false
  - jdk: openjdk13
    env: GRADLE_PUBLISH=false
dist: xenial
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
env:
  global:
  - secure: KJrNSzmjXRcJCuTacqMle+6rxjTSlLJQuwU1xwWXg6weQYi0Nc8Vb11JGW3jVEXfHjlR1e4WEwb6e4NaWGsEh9deSRYYD5xmzWAksRSMUySnwGXtWJAAveMsNH0hPsaS87uc2bRUhlQtNPljreajES0apxIvd0Ng4KGFM+18KFU=
  - secure: N+h31xFpA2eEfDC0y1ZYS76BS8nKJVufOL+217oOVdGpSwkfsRt3+Ds9FflktQdcXn+llA4G972L2iC06CBsPsszg0zuwbdtzlcLZ5g660s9vHTJGp9xUjFx6qZ4JquOlF0tz9GqIoyBw1ckU819dinCRstxbLMblHsgGNQmLPk=
  - secure: c1wIOMqzmlbFUYKsgq9Pz2grGxIM0k++GNZQOHFnh5G7UKPL/qtrb05Rax6O+sufATJ5nzmS9KIvEv2KFy2fcR0Ir8KPFzyYXFiQAMhbW/C13fIc/jFiPU+bJs1p1tNQFZ2rxzmeE46HjDaLN/2Bq6FQXz9v+pDiG9YJ3GKWnUU=
  - secure: jdLG4/zUrrdRTiF4nbCxoC75uuvbgBwIT/ra8uk+i71h2kefPpu54Qq/ppBIM8Pwa/IxP8a3BGOsaQ1oVjCLJ+dnos0fDeUmqWpy+xqm72kQXiuVxEMD3Ehd4x7i0HEe5jQf3sGj41IB0/DPcjajSKCCt5CUrdWHQeJxetmPQbk=
cache:
  directories:
  - "$HOME/.gradle"
